name: FunCombat
version: 1.8
main: fr.reaamz.funcombat.FunCombat

commands:
 sethub:
  description: Permet de set la location du Hub
  usage: /<command>

 hub:
  description: Retourne au Hub
  usage: /<command>

 gethub:
  description: Retourne la location du Hub
  usage: /<command>

 resethubdata:
  description: Reset toutes le data du Hub
  usage: /<command>

 getmenu:
  description: test
  usage: /<command>

 grade:
  description: changement de grade
  usage: /<command>

 uuid:
  description: uuid
  usage: /<command>

 setjump:
  description: setjump [DO THEM IN ORDER OR IT WILL NOT WORK]
  usage: /<command> <JUMPNAME> [startZone;startBlock;endBlock] {DO THEM IN ORDER OR IT WILL NOT WORK}